all:
  vars:
    ansible_user: yitao

  children:
    k3s:
      hosts:
        yl-04.lab.uvalight.net:
        yl-05.lab.uvalight.net:
    k3s_server:
      hosts:
        yl-04.lab.uvalight.net:
    k3s_worker:
      hosts:
        yl-05.lab.uvalight.net:
    edge:
      hosts:
        yl-01.lab.uvalight.net:
        yl-02.lab.uvalight.net:
        yl-03.lab.uvalight.net:
        yl-06.lab.uvalight.net:
    faasunits:
      hosts:
        yl-01.lab.uvalight.net:
          node_id: edge1
        yl-02.lab.uvalight.net:
          node_id: edge2
        yl-03.lab.uvalight.net:
          node_id: edge3
        yl-04.lab.uvalight.net:
          node_id: cloud
        yl-05.lab.uvalight.net:
          node_id: cloud
        yl-06.lab.uvalight.net:
          node_id: edge4
    data:
      hosts:
        yl-01.lab.uvalight.net:


