- name: Deploy faasd to edge nodes
  hosts: edge
  become: yes
  roles:
    - faasd

- name: Install Node exporter
  hosts: edge
  become: yes
  tasks:
  - name: Download node-exporter binary
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter.tar.gz

  - name: Extract node-exporter
    unarchive:
      src: /tmp/node_exporter.tar.gz
      dest: /opt/
      remote_src: yes

  - name: Symlink node_exporter binary
    file:
      src: /opt/node_exporter-1.8.0.linux-amd64/node_exporter
      dest: /usr/local/bin/node_exporter
      state: link
      force: yes

  - name: Create node-exporter systemd service
    copy:
      dest: /etc/systemd/system/node-exporter.service
      content: |
        [Unit]
        Description=Prometheus Node Exporter
        After=network.target

        [Service]
        ExecStart=/usr/local/bin/node_exporter
        Restart=always

        [Install]
        WantedBy=default.target
      mode: '0644'

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes

  - name: Enable and start node-exporter
    systemd:
      name: node-exporter
      enabled: yes
      state: started

- name: Overwrite prometheus.yml with full config (faasd + node-exporter)
  hosts: edge
  become: yes
  tasks:
    - name: Set local node_exporter target
      set_fact:
        node_exporter_target: "{{ inventory_hostname }}:9100"

    - name: Write full prometheus.yml
      copy:
        dest: /var/lib/faasd/prometheus.yml
        content: |
          global:
            scrape_interval:     15s
            evaluation_interval: 15s

          alerting:
            alertmanagers:
              - static_configs:
                  - targets: []

          rule_files: []

          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: ['{{ node_exporter_target }}']

            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'gateway'
              static_configs:
                - targets: ['gateway:8082']

            - job_name: 'provider'
              static_configs:
                - targets: ['faasd-provider:8081']
      notify: Restart faasd



  handlers:
    - name: Restart faasd
      become: yes
      shell: systemctl restart faasd



